ALTER TABLE host_rooms ADD COLUMN IF NOT EXISTS mode2d_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE host_rooms ADD COLUMN IF NOT EXISTS mode3d_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE host_rooms ADD COLUMN IF NOT EXISTS room_theme TEXT DEFAULT 'default';
